nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  core:
    npmAlwaysAuth: true
    npmAuthIdent: '${AZURE_DEVOPS_PAT:-fallback}'
    npmRegistryServer: 'https://pkgs.dev.azure.com/smartcraftsoftware/_packaging/smartcraftsoftware/npm/registry/'
  hugeicons-pro:
    npmAlwaysAuth: true
    npmAuthToken: '${VITE_HUGEICON_PRO_KEY-fallback}'
    npmRegistryServer: 'https://npm.hugeicons.com/'