/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoltageDropRouteImport } from './routes/voltage-drop'
import { Route as StandardSizesRouteImport } from './routes/standard-sizes'
import { Route as ResistivityRouteImport } from './routes/resistivity'
import { Route as PowerLossRouteImport } from './routes/power-loss'
import { Route as DeratingRouteImport } from './routes/derating'
import { Route as CrossSectionRouteImport } from './routes/cross-section'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IndexRouteImport } from './routes/index'

const VoltageDropRoute = VoltageDropRouteImport.update({
  id: '/voltage-drop',
  path: '/voltage-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardSizesRoute = StandardSizesRouteImport.update({
  id: '/standard-sizes',
  path: '/standard-sizes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResistivityRoute = ResistivityRouteImport.update({
  id: '/resistivity',
  path: '/resistivity',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerLossRoute = PowerLossRouteImport.update({
  id: '/power-loss',
  path: '/power-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const DeratingRoute = DeratingRouteImport.update({
  id: '/derating',
  path: '/derating',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossSectionRoute = CrossSectionRouteImport.update({
  id: '/cross-section',
  path: '/cross-section',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/cross-section': typeof CrossSectionRoute
  '/derating': typeof DeratingRoute
  '/power-loss': typeof PowerLossRoute
  '/resistivity': typeof ResistivityRoute
  '/standard-sizes': typeof StandardSizesRoute
  '/voltage-drop': typeof VoltageDropRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/cross-section': typeof CrossSectionRoute
  '/derating': typeof DeratingRoute
  '/power-loss': typeof PowerLossRoute
  '/resistivity': typeof ResistivityRoute
  '/standard-sizes': typeof StandardSizesRoute
  '/voltage-drop': typeof VoltageDropRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/cross-section': typeof CrossSectionRoute
  '/derating': typeof DeratingRoute
  '/power-loss': typeof PowerLossRoute
  '/resistivity': typeof ResistivityRoute
  '/standard-sizes': typeof StandardSizesRoute
  '/voltage-drop': typeof VoltageDropRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/cross-section'
    | '/derating'
    | '/power-loss'
    | '/resistivity'
    | '/standard-sizes'
    | '/voltage-drop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas'
    | '/cross-section'
    | '/derating'
    | '/power-loss'
    | '/resistivity'
    | '/standard-sizes'
    | '/voltage-drop'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/cross-section'
    | '/derating'
    | '/power-loss'
    | '/resistivity'
    | '/standard-sizes'
    | '/voltage-drop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRoute
  CrossSectionRoute: typeof CrossSectionRoute
  DeratingRoute: typeof DeratingRoute
  PowerLossRoute: typeof PowerLossRoute
  ResistivityRoute: typeof ResistivityRoute
  StandardSizesRoute: typeof StandardSizesRoute
  VoltageDropRoute: typeof VoltageDropRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voltage-drop': {
      id: '/voltage-drop'
      path: '/voltage-drop'
      fullPath: '/voltage-drop'
      preLoaderRoute: typeof VoltageDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard-sizes': {
      id: '/standard-sizes'
      path: '/standard-sizes'
      fullPath: '/standard-sizes'
      preLoaderRoute: typeof StandardSizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resistivity': {
      id: '/resistivity'
      path: '/resistivity'
      fullPath: '/resistivity'
      preLoaderRoute: typeof ResistivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-loss': {
      id: '/power-loss'
      path: '/power-loss'
      fullPath: '/power-loss'
      preLoaderRoute: typeof PowerLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derating': {
      id: '/derating'
      path: '/derating'
      fullPath: '/derating'
      preLoaderRoute: typeof DeratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-section': {
      id: '/cross-section'
      path: '/cross-section'
      fullPath: '/cross-section'
      preLoaderRoute: typeof CrossSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRoute,
  CrossSectionRoute: CrossSectionRoute,
  DeratingRoute: DeratingRoute,
  PowerLossRoute: PowerLossRoute,
  ResistivityRoute: ResistivityRoute,
  StandardSizesRoute: StandardSizesRoute,
  VoltageDropRoute: VoltageDropRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
